# Nouveau (8 joints : rail + 7 bras)
fr3_sur_rail:  # ‚Üê Nom du groupe dans le SRDF
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_timeout: 0.005
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_attempts: 3